version: "{build}"
clone_depth: 1
environment:
  matrix:
    - nodejs_version: "0"
    - nodejs_version: "4"
    - nodejs_version: "6"
matrix:
  fast_finish: true
cache:
  - node_modules
platform:
  - x86
install:
  - ps: Install-Product node $env:nodejs_version $env:platform

  - npm config set spin false
  - npm install
  - node_modules/.bin/jspm config registries.github.timeouts.download 600
test_script:
  - node --version
  - npm --version
  - npm test
build: off
